language: julia
os:
  - osx
  - linux
julia:
  - 1.2
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; import NMFk; cd(joinpath(dirname(pathof(NMFk)))); Pkg.add("Coverage"); import Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
